# Generated by Django 3.0.5 on 2020-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200724_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
    ]
