# Generated by Django 3.0.5 on 2020-07-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_images_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
