# Generated by Django 3.0.5 on 2020-07-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job', models.CharField(choices=[('Excavation', 'Excavation'), ('Demolition', 'Demolition'), ('Snow removal', 'Snow removal'), ('Asphalt paving', 'Asphalt paving'), ('Concrete pavement', 'Concret pavement'), ('Commercila Pavement', 'Commercial Pavement')], max_length=256)),
                ('picture', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
