# Generated by Django 3.0.5 on 2020-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
