# Generated by Django 3.0.5 on 2020-07-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200725_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='job',
            field=models.CharField(choices=[('Excavation', 'Excavation'), ('Demolition', 'Demolition'), ('Snow', 'Snow'), ('Asphalt paving', 'Asphalt paving'), ('Concrete pavement', 'Concret pavement'), ('Commercila Pavement', 'Commercial Pavement')], max_length=256),
        ),
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
